feat!: overhaul and simplify configuration
- No more terraform.tfvars - edit examples/main.tf directly
- Add support for deactivating all public IP addresses for servers - a
  gateway is required to make the master node publicly accessible and to
  provide internet access
- Write ssh configuration and ssh and scp tools that directly connects to the
  main server and sets up the main server as a jump host the other
  servers
- Improve quoting in kubeconfig shell scripts
- Generate kubeconfig in cluster directory and not outside
- Store SSH keys at hcloud via a simple string map
- Simplify output variables and provide detailed information about
  node name, type, and public and private IP addresses
- Convert node groups to node pools
- Make location configuration generally available - it's simpler than
  selecting the data center
- Add protection against manual deletion of resources
- Fix tflint warnings
- Add reference hetzner-k3s
- Change node number to consist of two digits
- Remove datacenter variable in favor of location
- Use placement groups for nodes
- Rename master to main
- Add debugging instructions

diff --git a/templates/kubeconfig_setkubeconfig b/templates/kubeconfig_setkubeconfig
--- a/templates/kubeconfig_setkubeconfig
+++ b/templates/kubeconfig_setkubeconfig
@@ -1,37 +1,37 @@
-#!/bin/bash
+#!/usr/bin/env bash
+set -eEuo pipefail
 
-MASTER_NODE_HOST=${master_ipv4}
-MASTER_NODE_USER=root
-
-K8S_API=https://${master_ipv4}:6443
-CLUSTER=${cluster_name}
+CLUSTER="${cluster_name}"
+MAIN_NODE_HOST="${cluster_ip}"
+K8S_API="https://${cluster_ip}:6443"
+export KUBECONFIG="${cwd}/.kube/config"
 
 ###################
 
 for requirement in kubectl ssh jq; do
-    which $requirement >/dev/null || {
-        echo -e "\e[1mMissing\e[0m: $requirement not found in PATH" >&2
-        echo "" >&2
-        echo "This script requires: kubectl, ssh, jq" >&2
-        exit 1
-    }
+	which $requirement >/dev/null || {
+		echo -e "\e[1mMissing\e[0m: $requirement not found in PATH" >&2
+		echo "" >&2
+		echo "This script requires: kubectl, ssh, jq" >&2
+		exit 1
+	}
 done
 
-echo "Checking SSH connection to $MASTER_NODE_HOST"
-if ! ssh -q -o StrictHostKeyChecking=no -o BatchMode=yes -o ConnectTimeout=5 $MASTER_NODE_USER@$MASTER_NODE_HOST exit; then
-    echo
-    echo "Can't connect... please check your ssh key and config"
-    echo
-    exit 1
+echo "Checking SSH connection to $MAIN_NODE_HOST"
+if ! "${cwd}/ssh-node" -q -o BatchMode=yes -o ConnectTimeout=5 cluster exit; then
+	echo
+	echo "Can't connect... please check your ssh key and config"
+	echo
+	exit 1
 fi
 
 sshrun() {
-    ssh -q -o StrictHostKeyChecking=no $MASTER_NODE_USER@$MASTER_NODE_HOST -- $@
+	"${cwd}/ssh-node" -q cluster "$@"
 }
 
 while ! sshrun 'kubectl cluster-info'; do
-    echo "Waiting cluster"
-    sleep 2
+	echo "Waiting cluster"
+	sleep 2
 done
 
 rawconfig="$(sshrun kubectl config view -ojson --raw)"
@@ -40,40 +40,40 @@ cacert_file=$(mktemp)
 cert_file=$(mktemp)
 key_file=$(mktemp)
 
-echo "$rawconfig" | jq -r '.clusters[0].cluster["certificate-authority-data"]' | base64 -d >$cacert_file
-echo "$rawconfig" | jq -r '.users[0].user["client-certificate-data"]' | base64 -d >$cert_file
-echo "$rawconfig" | jq -r '.users[0].user["client-key-data"]' | base64 -d >$key_file
+echo "$rawconfig" | jq -r '.clusters[0].cluster["certificate-authority-data"]' | base64 -d >"$cacert_file"
+echo "$rawconfig" | jq -r '.users[0].user["client-certificate-data"]' | base64 -d >"$cert_file"
+echo "$rawconfig" | jq -r '.users[0].user["client-key-data"]' | base64 -d >"$key_file"
 
 # create cluster entry in local kubectl config
-kubectl config set-cluster $CLUSTER \
-    --server=$K8S_API \
-    --certificate-authority=$cacert_file \
-    --embed-certs=true
+kubectl config set-cluster "$CLUSTER" \
+	"--server=$K8S_API" \
+	"--certificate-authority=$cacert_file" \
+	--embed-certs=true
 
-kubectl config set-credentials $CLUSTER \
-    --client-certificate=$cert_file \
-    --client-key=$key_file \
-    --embed-certs=true
+kubectl config set-credentials "$CLUSTER" \
+	"--client-certificate=$cert_file" \
+	"--client-key=$key_file" \
+	--embed-certs=true
 
 # create oidc user if oidc is enabled
 %{ if oidc_enabled ~}
 kubectl config set-credentials oidc \
-    --exec-api-version=client.authentication.k8s.io/v1beta1 \
-    --exec-command=kubectl \
-    --exec-arg=oidc-login \
-    --exec-arg=get-token \
-    --exec-arg=--oidc-issuer-url=${oidc_issuer_url} \
-    --exec-arg=--oidc-client-id=${oidc_client_id} \
-    --exec-arg=--oidc-client-secret=${oidc_client_secret} \
-    --exec-arg=--oidc-extra-scope=profile \
-    --exec-arg=--oidc-extra-scope=groups
+	--exec-api-version=client.authentication.k8s.io/v1beta1 \
+	--exec-command=kubectl \
+	--exec-arg=oidc-login \
+	--exec-arg=get-token \
+	"--exec-arg=--oidc-issuer-url=${oidc_issuer_url}" \
+	"--exec-arg=--oidc-client-id=${oidc_client_id}" \
+	"--exec-arg=--oidc-client-secret=${oidc_client_secret}" \
+	--exec-arg=--oidc-extra-scope=profile \
+	--exec-arg=--oidc-extra-scope=groups
 %{ endif ~}
 
-rm -f $cacert_file $cert_file $key_file
+rm -f "$cacert_file" "$cert_file" "$key_file"
 
 # set the appropriate user
-kubectl config set-context $CLUSTER \
-    --cluster=$CLUSTER \
-    %{ if oidc_enabled }--user=oidc%{ else }--user=$CLUSTER%{ endif }
+kubectl config set-context "$CLUSTER" \
+	"--cluster=$CLUSTER" \
+	%{ if oidc_enabled }--user=oidc%{ else }"--user=$CLUSTER"%{ endif }
 
-kubectl config use-context $CLUSTER
+kubectl config use-context "$CLUSTER"
