feat(setkubeconfig): make script wait until SSH connection is possible

diff --git a/templates/kubeconfig_setkubeconfig b/templates/kubeconfig_setkubeconfig
--- a/templates/kubeconfig_setkubeconfig
+++ b/templates/kubeconfig_setkubeconfig
@@ -18,19 +18,19 @@ for requirement in kubectl ssh jq; do
 done
 
 echo "Checking SSH connection to $MAIN_NODE_HOST"
-if ! "${cwd}/ssh-node" -q -o ConnectTimeout=5 cluster exit; then
+while ! "${cwd}/ssh-node" -q -o ConnectTimeout=5 cluster exit; do
 	echo
-	echo "Can't connect... please check your ssh key and config"
+	echo "Can't connect... retrying."
 	echo
-	exit 1
-fi
+	sleep 2
+done
 
 sshrun() {
 	"${cwd}/ssh-node" -q cluster "$@"
 }
 
 while ! sshrun 'kubectl cluster-info'; do
-	echo "Waiting cluster"
+	echo "Waiting for cluster to become ready."
 	sleep 2
 done
 
@@ -62,9 +62,9 @@ kubectl config set-credentials oidc \
 	--exec-command=kubectl \
 	--exec-arg=oidc-login \
 	--exec-arg=get-token \
-	"--exec-arg=--oidc-issuer-url=${oidc_issuer_url}" \
-	"--exec-arg=--oidc-client-id=${oidc_client_id}" \
-	"--exec-arg=--oidc-client-secret=${oidc_client_secret}" \
+	--exec-arg=--oidc-issuer-url="${oidc_issuer_url}" \
+	--exec-arg=--oidc-client-id="${oidc_client_id}" \
+	--exec-arg=--oidc-client-secret="${oidc_client_secret}" \
 	--exec-arg=--oidc-extra-scope=profile \
 	--exec-arg=--oidc-extra-scope=groups
 %{ endif ~}
