fix(setkubeconfig): remove KUBECONFIG setting from scripts
Using the default setting make it more convenient for system wide access
to the cluster.

diff --git a/templates/kubeconfig_setkubeconfig b/templates/kubeconfig_setkubeconfig
--- a/templates/kubeconfig_setkubeconfig
+++ b/templates/kubeconfig_setkubeconfig
@@ -7,7 +7,6 @@ set -eEuo pipefail
 CLUSTER="${cluster_name}"
 MAIN_NODE_HOST="${cluster_ip}"
 K8S_API="https://${cluster_ip}:6443"
-export KUBECONFIG="${cwd}/.kube/config"
 
 ###################
 
@@ -21,12 +20,13 @@ for requirement in kubectl ssh jq; do
 done
 
 echo "Checking SSH connection to $MAIN_NODE_HOST"
-while ! "${cwd}/ssh-node" -q -o ConnectTimeout=5 cluster exit; do
+if ! "${cwd}/ssh-node" -q -o ConnectTimeout=5 cluster exit; then
+	sleep 10
 	echo
-	echo "Can't connect... retrying."
+	echo "Can't connect..."
 	echo
-	sleep 2
-done
+	exit 1
+fi
 
 sshrun() {
 	"${cwd}/ssh-node" -q cluster "$@"
